sensors:
  - far_clipping_plane_distance: 2.0
    filtered_cloud_topic: filtered_cloud
    image_topic: /top_camera_realsense/depth/image_rect_raw
    max_update_rate: 1.0
    near_clipping_plane_distance: 0.05
    padding_offset: 0.05
    padding_scale: 4.0
    queue_size: 5
    sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    shadow_threshold: 0.2